import type { AdminMenuItem } from '@/types/admin'

export const adminMenus: AdminMenuItem[] = [
  {
    key: 'dashboard',
    label: '工作台',
    icon: 'DataBoard',
    route: '/dashboard/index',
    menuPermission: 'menu.dashboard',
    pagePermission: 'page.dashboard.index',
  },
  {
    key: 'verify',
    label: '实名认证',
    icon: 'CircleCheck',
    menuPermission: 'menu.verify',
    children: [
      {
        key: 'verify-pending',
        label: '待审核',
        icon: 'CircleCheck',
        route: '/verify/pending',
        pagePermission: 'page.verify.pending',
      },
      {
        key: 'verify-history',
        label: '审核历史',
        icon: 'Document',
        route: '/verify/history',
        pagePermission: 'page.verify.history',
      },
    ],
  },
  {
    key: 'referral',
    label: '邀请裂变',
    icon: 'Connection',
    menuPermission: 'menu.referral',
    children: [
      {
        key: 'referral-records',
        label: '邀请记录',
        icon: 'Tickets',
        route: '/referral/records',
        pagePermission: 'page.referral.records',
      },
      {
        key: 'referral-risk',
        label: '异常邀请',
        icon: 'Warning',
        route: '/referral/risk',
        pagePermission: 'page.referral.risk',
      },
      {
        key: 'referral-policies',
        label: '邀请规则',
        icon: 'SetUp',
        route: '/referral/policies',
        pagePermission: 'page.referral.policies',
      },
      {
        key: 'referral-eligibility',
        label: '邀请资格',
        icon: 'Medal',
        route: '/referral/eligibility',
        pagePermission: 'page.referral.eligibility',
      },
    ],
  },
  {
    key: 'membership',
    label: '会员中心',
    icon: 'Medal',
    menuPermission: 'menu.membership',
    children: [
      {
        key: 'membership-products',
        label: '会员产品',
        icon: 'Box',
        route: '/membership/products',
        pagePermission: 'page.membership.products',
      },
      {
        key: 'membership-accounts',
        label: '会员账户',
        icon: 'UserFilled',
        route: '/membership/accounts',
        pagePermission: 'page.membership.accounts',
      },
    ],
  },
  {
    key: 'payment',
    label: '订单中心',
    icon: 'CreditCard',
    menuPermission: 'menu.payment',
    children: [
      {
        key: 'payment-orders',
        label: '支付订单',
        icon: 'Coin',
        route: '/payment/orders',
        pagePermission: 'page.payment.orders',
      },
      {
        key: 'payment-transactions',
        label: '支付流水',
        icon: 'Histogram',
        route: '/payment/transactions',
        pagePermission: 'page.payment.transactions',
      },
    ],
  },
  {
    key: 'refund',
    label: '退款中心',
    icon: 'Wallet',
    menuPermission: 'menu.refund',
    children: [
      {
        key: 'refund-orders',
        label: '退款单',
        icon: 'Tickets',
        route: '/refund/orders',
        pagePermission: 'page.refund.orders',
      },
      {
        key: 'refund-logs',
        label: '退款日志',
        icon: 'Memo',
        route: '/refund/logs',
        pagePermission: 'page.refund.logs',
      },
    ],
  },
  {
    key: 'content',
    label: '页面配置',
    icon: 'MagicStick',
    menuPermission: 'menu.content',
    children: [
      {
        key: 'content-templates',
        label: '场景模板',
        icon: 'Files',
        route: '/content/templates',
        pagePermission: 'page.content.templates',
      },
    ],
  },
  {
    key: 'system',
    label: '系统管理',
    icon: 'Setting',
    menuPermission: 'menu.system',
    children: [
      {
        key: 'system-ai-resume-governance',
        label: 'AI 简历治理',
        icon: 'MagicStick',
        route: '/system/ai-resume-governance',
        pagePermission: 'page.system.ai-resume-governance',
        pagePermissionFallbacks: ['page.system.operation-logs'],
      },
      {
        key: 'system-admin-users',
        label: '后台账号',
        icon: 'Avatar',
        route: '/system/admin-users',
        pagePermission: 'page.system.admin-users',
      },
      {
        key: 'system-roles',
        label: '角色管理',
        icon: 'Postcard',
        route: '/system/roles',
        pagePermission: 'page.system.roles',
      },
      {
        key: 'system-operation-logs',
        label: '操作日志',
        icon: 'List',
        route: '/system/operation-logs',
        pagePermission: 'page.system.operation-logs',
      },
    ],
  },
]
