export const PERMISSIONS = {
  menu: {
    dashboard: 'menu.dashboard',
    verify: 'menu.verify',
    referral: 'menu.referral',
    membership: 'menu.membership',
    content: 'menu.content',
    system: 'menu.system',
  },
  page: {
    dashboardIndex: 'page.dashboard.index',
    verifyPending: 'page.verify.pending',
    verifyHistory: 'page.verify.history',
    verifyDetail: 'page.verify.detail',
    referralRisk: 'page.referral.risk',
    referralEligibility: 'page.referral.eligibility',
    membershipProducts: 'page.membership.products',
    membershipAccounts: 'page.membership.accounts',
    contentTemplates: 'page.content.templates',
    systemAdminUsers: 'page.system.admin-users',
  },
  action: {
    verifyApprove: 'action.verify.approve',
    verifyReject: 'action.verify.reject',
    referralRiskApprove: 'action.referral.risk.approve',
    referralRiskInvalidate: 'action.referral.risk.invalidate',
    referralRiskResolve: 'action.referral.risk.resolve',
    referralEligibilityGrant: 'action.referral.eligibility.grant',
    referralEligibilityRevoke: 'action.referral.eligibility.revoke',
    referralEligibilityExtend: 'action.referral.eligibility.extend',
    membershipProductCreate: 'action.membership.product.create',
    membershipAccountOpen: 'action.membership.account.open',
    membershipAccountExtend: 'action.membership.account.extend',
    membershipAccountClose: 'action.membership.account.close',
    contentTemplateCreate: 'action.content.template.create',
    contentTemplateEdit: 'action.content.template.edit',
    contentTemplatePublish: 'action.content.template.publish',
    contentTemplateRollback: 'action.content.template.rollback',
  },
} as const;
